name: docker publish

on: push

jobs:
  build-tools-images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          - name: SLiM
            version: 4.2.2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: metadata  # store tags/labels in this workflow id
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/tools/${{ matrix.container.name }}
          tags: |
            type=raw,value=${{ matrix.container.version }} 

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: docker/tools/${{ matrix.container.name }}
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          build-args: |
            VERSION=${{ matrix.container.version }}
